const questions = [
    { word: "ὁ", cat: "lidwoord", answers: ["nom ev m"] },
    { word: "τοῦ", cat: "lidwoord", answers: ["gen ev m", "gen ev n"] },
    { word: "τῷ", cat: "lidwoord", answers: ["dat ev m", "dat ev n"] },
    { word: "τόν", cat: "lidwoord", answers: ["acc ev m"] },
    { word: "οἱ", cat: "lidwoord", answers: ["nom mv m"] },
    { word: "τῶν", cat: "lidwoord", answers: ["gen mv m", "gen mv f","gen mv n"] },
    { word: "τοῖς", cat: "lidwoord", answers: ["dat mv m", "dat mv n"] },
    { word: "τούς", cat: "lidwoord", answers: ["acc mv m"] },
	{ word: "ἡ", cat: "lidwoord", answers: ["nom ev f"] },
    { word: "τῆς", cat: "lidwoord", answers: ["gen ev f"] },
    { word: "τῇ", cat: "lidwoord", answers: ["dat ev f"] },
    { word: "τήν", cat: "lidwoord", answers: ["acc ev f"] },
    { word: "αἱ", cat: "lidwoord", answers: ["nom mv f"] },
    { word: "ταῖς", cat: "lidwoord", answers: ["dat mv f"] },
    { word: "τάς", cat: "lidwoord", answers: ["acc mv f"] },
	{ word: "τό", cat: "lidwoord", answers: ["nom ev n", "acc ev n"] },
	{ word: "τά", cat: "lidwoord", answers: ["nom mv n", "acc mv n"] },     
 	{ word: "μάχη", cat: "μάχη", answers: ["nom ev f"] },
	{ word: "μάχης", cat: "μάχη", answers: ["gen ev f"] },
	{ word: "μάχῃ", cat: "μάχη", answers: ["dat ev f"] },
	{ word: "μάχην", cat: "μάχη", answers: ["acc ev f"] },
	{ word: "μάχαι", cat: "μάχη", answers: ["nom mv f"] },
	{ word: "μαχῶν", cat: "μάχη", answers: ["gen mv f"] },
	{ word: "μάχαις", cat: "μάχη", answers: ["dat mv f"] },
	{ word: "μάχας", cat: "μάχη", answers: ["acc mv f"] },
	{ word: "χώρα", cat: "χώρα", answers: ["nom ev f"] },
	{ word: "χώρας", cat: "χώρα", answers: ["gen ev f","acc mv f"] },
	{ word: "χώρᾳ", cat: "χώρα", answers: ["dat ev f"] },
	{ word: "χώραν", cat: "χώρα", answers: ["acc ev f"] },
	{ word: "χῶραι", cat: "χώρα", answers: ["nom mv f"] },
	{ word: "χωρῶν", cat: "χώρα", answers: ["gen mv f"] },
	{ word: "χώραις", cat: "χώρα", answers: ["dat mv f"] },
	{ word: "θάλαττα", cat: "θάλαττα", answers: ["nom ev f"] },
	{ word: "θαλάττης", cat: "θάλαττα", answers: ["gen ev f"] },
	{ word: "θαλάττῃ", cat: "θάλαττα", answers: ["dat ev f"] },
	{ word: "θάλατταν", cat: "θάλαττα", answers: ["acc ev f"] },
	{ word: "θάλατται", cat: "θάλαττα", answers: ["nom mv f"] },
	{ word: "θαλαττῶν", cat: "θάλαττα", answers: ["gen mv f"] },
	{ word: "θαλάτταις", cat: "θάλαττα", answers: ["dat mv f"] },
	{ word: "θαλάττας", cat: "θάλαττα", answers: ["acc mv f"] },
	{ word: "δεσπότης", cat: "δεσπότης", answers: ["nom ev m"] },
	{ word: "δεσπότου", cat: "δεσπότης", answers: ["gen ev m"] },
	{ word: "δεσπότῃ", cat: "δεσπότης", answers: ["dat ev m"] },
	{ word: "δεσπότην", cat: "δεσπότης", answers: ["acc ev m"] },
	{ word: "δεσπόται", cat: "δεσπότης", answers: ["nom mv m"] },
	{ word: "δεσποτῶν", cat: "δεσπότης", answers: ["gen mv m"] },
	{ word: "δεσπόταις", cat: "δεσπότης", answers: ["dat mv m"] },
	{ word: "δεσπότας", cat: "δεσπότης", answers: ["acc mv m"] },
	{ word: "δοῦλος", cat: "δοῦλος", answers: ["nom ev m"] },
	{ word: "δούλου", cat: "δοῦλος", answers: ["gen ev m"] },
	{ word: "δούλῳ", cat: "δοῦλος", answers: ["dat ev m"] },
	{ word: "δοῦλον", cat: "δοῦλος", answers: ["acc ev m"] },
	{ word: "δοῦλοι", cat: "δοῦλος", answers: ["nom mv m"] },
	{ word: "δούλων", cat: "δοῦλος", answers: ["gen mv m"] },
	{ word: "δούλοις", cat: "δοῦλος", answers: ["dat mv m"] },
	{ word: "δούλους", cat: "δοῦλος", answers: ["acc mv m"] },
	{ word: "θηρίον", cat: "θηρίον", answers: ["nom ev n", "acc ev n"] },	
	{ word: "θηρίου", cat: "θηρίον", answers: ["gen ev n"] },
	{ word: "θηρίῳ", cat: "θηρίον", answers: ["dat ev n"] },
	{ word: "θηρία", cat: "θηρίον", answers: ["nom mv n", "acc mv n"] },	
	{ word: "θηρίων", cat: "θηρίον", answers: ["gen mv n"] },
	{ word: "θηρίοις", cat: "θηρίον", answers: ["dat mv n"] },
	{ word: "σωτήρ", cat: "σωτήρ", answers: ["nom ev m"] },
	{ word: "σωτῆρος", cat: "σωτήρ", answers: ["gen ev m"] },
	{ word: "σωτῆρι", cat: "σωτήρ", answers: ["dat ev m"] },
	{ word: "σωτῆρα", cat: "σωτήρ", answers: ["acc ev m"] },
	{ word: "σωτῆρες", cat: "σωτήρ", answers: ["nom mv m"] },
	{ word: "σωτήρων", cat: "σωτήρ", answers: ["gen mv m"] },
	{ word: "σωτῆρσι(ν)", cat: "σωτήρ", answers: ["dat mv m"] },
	{ word: "σωτῆρα", cat: "σωτήρ", answers: ["acc mv m"] },
	{ word: "γυνή", cat: "γυνή", answers: ["nom ev f"] },
	{ word: "γυναικός", cat: "γυνή", answers: ["gen ev f"] },
	{ word: "γυναικί", cat: "γυνή", answers: ["dat ev f"] },
	{ word: "γυναῖκα", cat: "γυνή", answers: ["acc ev f"] },
	{ word: "γυναῖκες", cat: "γυνή", answers: ["nom mv f"] },
	{ word: "γυναικῶν", cat: "γυνή", answers: ["gen mv f"] },
	{ word: "γυναιξί(ν)", cat: "γυνή", answers: ["dat mv f"] },
	{ word: "γυναῖκας", cat: "γυνή", answers: ["acc mv f"] },
	{ word: "λέων", cat: "λέων", answers: ["nom ev m"] },
	{ word: "λέοντος", cat: "λέων", answers: ["gen ev m"] },
	{ word: "λέοντι", cat: "λέων", answers: ["dat ev m"] },
	{ word: "λέοντα", cat: "λέων", answers: ["acc ev m"] },
	{ word: "λέοντες", cat: "λέων", answers: ["nom mv m"] },
	{ word: "λεόντων", cat: "λέων", answers: ["gen mv m"] },
	{ word: "λέουσι(ν)", cat: "λέων", answers: ["dat mv m"] },
	{ word: "λέοντας", cat: "λέων", answers: ["acc mv m"] },
	{ word: "σῶμα", cat: "σῶμα", answers: ["nom ev n", "acc ev n"] },	
	{ word: "σώματος", cat: "σῶμα", answers: ["gen ev n"] },
	{ word: "σώματι", cat: "σῶμα", answers: ["dat ev n"] },
	{ word: "σώματα", cat: "σῶμα", answers: ["nom mv n", "acc mv n"] },	
	{ word: "σωμάτων", cat: "σῶμα", answers: ["gen mv n"] },
	{ word: "σώμασι(ν)", cat: "σῶμα", answers: ["dat mv n"] },
	
		
];

