export const qGreekVerb = [
	{ "word": "λύω", "cat": "λύω", "answers": ["ind praes 1e-ev act"] },
	{ "word": "λύεις", "cat": "λύω", "answers": ["ind praes 2e-ev act"] },
	{ "word": "λύει", "cat": "λύω", "answers": ["ind praes 3e-ev act"] },
	{ "word": "λύομεν", "cat": "λύω", "answers": ["ind praes 1e-mv act"] },
	{ "word": "λύετε", "cat": "λύω", "answers": ["ind praes 2e-mv act"] },
	{ "word": "λύουσι(ν)", "cat": "λύω", "answers": ["ind praes 3e-mv act"] },
	{ "word": "ἔλυον", "cat": "λύω", "answers": ["ind impf 1e-ev act"] },
	{ "word": "ἔλυες", "cat": "λύω", "answers": ["ind impf 2e-ev act"] },
	{ "word": "ἔλυε", "cat": "λύω", "answers": ["ind impf 3e-ev act"] },
	{ "word": "ἐλύομεν", "cat": "λύω", "answers": ["ind impf 1e-mv act"] },
	{ "word": "ἐλύετε", "cat": "λύω", "answers": ["ind impf 2e-mv act"] },
	{ "word": "ἔλυον", "cat": "λύω", "answers": ["ind impf 3e-mv act"] },
	{ "word": "λύσω", "cat": "λύω", "answers": ["ind fut 1e-ev act"] },
	{ "word": "λύσεις", "cat": "λύω", "answers": ["ind fut 2e-ev act"] },
	{ "word": "λύσει", "cat": "λύω", "answers": ["ind fut 3e-ev act"] },
	{ "word": "λύσομεν", "cat": "λύω", "answers": ["ind fut 1e-mv act"] },
	{ "word": "λύσετε", "cat": "λύω", "answers": ["ind fut 2e-mv act"] },
	{ "word": "λύσουσι(ν)", "cat": "λύω", "answers": ["ind fut 3e-mv act"] },
];


export const qLatinVerb= [
	{ "word": "voco", "cat": "vocare", "answers": ["ind praes 1e-ev act"] },
	{ "word": "vocas", "cat": "vocare", "answers": ["ind praes 2e-ev act"] },
	{ "word": "vocat", "cat": "vocare", "answers": ["ind praes 3e-ev act"] },
	{ "word": "vocamus", "cat": "vocare", "answers": ["ind praes 1e-mv act"] },
	{ "word": "vocatis", "cat": "vocare", "answers": ["ind praes 2e-mv act"] },
	{ "word": "vocant", "cat": "vocare", "answers": ["ind praes 3e-mv act"] },

	{ "word": "vocor", "cat": "vocare", "answers": ["ind praes 1e-ev pass"] },
	{ "word": "vocaris", "cat": "vocare", "answers": ["ind praes 2e-ev pass"] },
	{ "word": "vocatur", "cat": "vocare", "answers": ["ind praes 3e-ev pass"] },
	{ "word": "vocamur", "cat": "vocare", "answers": ["ind praes 1e-mv pass"] },
	{ "word": "vocamini", "cat": "vocare", "answers": ["ind praes 2e-mv pass"] },
	{ "word": "vocantur", "cat": "vocare", "answers": ["ind praes 3e-mv pass"] },

	{ "word": "vocabam", "cat": "vocare", "answers": ["ind impf 1e-ev act"] },
	{ "word": "vocabas", "cat": "vocare", "answers": ["ind impf 2e-ev act"] },
	{ "word": "vocabat", "cat": "vocare", "answers": ["ind impf 3e-ev act"] },
	{ "word": "vocabamus", "cat": "vocare", "answers": ["ind impf 1e-mv act"] },
	{ "word": "vocabatis", "cat": "vocare", "answers": ["ind impf 2e-mv act"] },
	{ "word": "vocabant", "cat": "vocare", "answers": ["ind impf 3e-mv act"] },

	{ "word": "vocabar", "cat": "vocare", "answers": ["ind impf 1e-ev pass"] },
	{ "word": "vocabaris", "cat": "vocare", "answers": ["ind impf 2e-ev pass"] },
	{ "word": "vocabatur", "cat": "vocare", "answers": ["ind impf 3e-ev pass"] },
	{ "word": "vocabamur", "cat": "vocare", "answers": ["ind impf 1e-mv pass"] },
	{ "word": "vocabamini", "cat": "vocare", "answers": ["ind impf 2e-mv pass"] },
	{ "word": "vocabantur", "cat": "vocare", "answers": ["ind impf 3e-mv pass"] },

	{ "word": "vocabo", "cat": "vocare", "answers": ["ind fut 1e-ev act"] },
	{ "word": "vocabis", "cat": "vocare", "answers": ["ind fut 2e-ev act"] },
	{ "word": "vocabit", "cat": "vocare", "answers": ["ind fut 3e-ev act"] },
	{ "word": "vocabimus", "cat": "vocare", "answers": ["ind fut 1e-mv act"] },
	{ "word": "vocabitis", "cat": "vocare", "answers": ["ind fut 2e-mv act"] },
	{ "word": "vocabunt", "cat": "vocare", "answers": ["ind fut 3e-mv act"] },

	{ "word": "vocabor", "cat": "vocare", "answers": ["ind fut 1e-ev pass"] },
	{ "word": "vocaberis", "cat": "vocare", "answers": ["ind fut 2e-ev pass"] },
	{ "word": "vocabitur", "cat": "vocare", "answers": ["ind fut 3e-ev pass"] },
	{ "word": "vocabimur", "cat": "vocare", "answers": ["ind fut 1e-mv pass"] },
	{ "word": "vocabimini", "cat": "vocare", "answers": ["ind fut 2e-mv pass"] },
	{ "word": "vocabuntur", "cat": "vocare", "answers": ["ind fut 3e-mv pass"] },

	{ "word": "vocavi", "cat": "vocare", "answers": ["ind perf 1e-ev act"] },
	{ "word": "vocavisti", "cat": "vocare", "answers": ["ind perf 2e-ev act"] },
	{ "word": "vocavit", "cat": "vocare", "answers": ["ind perf 3e-ev act"] },
	{ "word": "vocavimus", "cat": "vocare", "answers": ["ind perf 1e-mv act"] },
	{ "word": "vocavistis", "cat": "vocare", "answers": ["ind perf 2e-mv act"] },
	{ "word": "vocaverunt", "cat": "vocare", "answers": ["ind perf 3e-mv act"] },

	{ "word": "vocaveram", "cat": "vocare", "answers": ["ind plqpf 1e-ev act"] },
	{ "word": "vocaveras", "cat": "vocare", "answers": ["ind plqpf 2e-ev act"] },
	{ "word": "vocaverat", "cat": "vocare", "answers": ["ind plqpf 3e-ev act"] },
	{ "word": "vocaveramus", "cat": "vocare", "answers": ["ind plqpf 1e-mv act"] },
	{ "word": "vocaveratis", "cat": "vocare", "answers": ["ind plqpf 2e-mv act"] },
	{ "word": "vocaverant", "cat": "vocare", "answers": ["ind plqpf 3e-mv act"] },

	{ "word": "vocavero", "cat": "vocare", "answers": ["ind fex 1e-ev act"] },
	{ "word": "vocaveris", "cat": "vocare", "answers": ["ind fex 2e-ev act"] },
	{ "word": "vocaverit", "cat": "vocare", "answers": ["ind fex 3e-ev act"] },
	{ "word": "vocaverimus", "cat": "vocare", "answers": ["ind fex 1e-mv act"] },
	{ "word": "vocaveritis", "cat": "vocare", "answers": ["ind fex 2e-mv act"] },
	{ "word": "vocaverint", "cat": "vocare", "answers": ["ind fex 3e-mv act"] },

	{ "word": "vocem", "cat": "vocare", "answers": ["conj praes 1e-ev act"] },
	{ "word": "voces", "cat": "vocare", "answers": ["conj praes 2e-ev act"] },
	{ "word": "vocet", "cat": "vocare", "answers": ["conj praes 3e-ev act"] },
	{ "word": "vocemus", "cat": "vocare", "answers": ["conj praes 1e-mv act"] },
	{ "word": "vocetis", "cat": "vocare", "answers": ["conj praes 2e-mv act"] },
	{ "word": "vocent", "cat": "vocare", "answers": ["conj praes 3e-mv act"] },

	{ "word": "vocer", "cat": "vocare", "answers": ["conj praes 1e-ev pass"] },
	{ "word": "voceris", "cat": "vocare", "answers": ["conj praes 2e-ev pass"] },
	{ "word": "vocetur", "cat": "vocare", "answers": ["conj praes 3e-ev pass"] },
	{ "word": "vocemur", "cat": "vocare", "answers": ["conj praes 1e-mv pass"] },
	{ "word": "vocemini", "cat": "vocare", "answers": ["conj praes 2e-mv pass"] },
	{ "word": "vocentur", "cat": "vocare", "answers": ["conj praes 3e-mv pass"] },

	{ "word": "vocarem", "cat": "vocare", "answers": ["conj impf 1e-ev act"] },
	{ "word": "vocares", "cat": "vocare", "answers": ["conj impf 2e-ev act"] },
	{ "word": "vocaret", "cat": "vocare", "answers": ["conj impf 3e-ev act"] },
	{ "word": "vocaremus", "cat": "vocare", "answers": ["conj impf 1e-mv act"] },
	{ "word": "vocaretis", "cat": "vocare", "answers": ["conj impf 2e-mv act"] },
	{ "word": "vocarent", "cat": "vocare", "answers": ["conj impf 3e-mv act"] },

	{ "word": "vocarer", "cat": "vocare", "answers": ["conj impf 1e-ev pass"] },
	{ "word": "vocareris", "cat": "vocare", "answers": ["conj impf 2e-ev pass"] },
	{ "word": "vocaretur", "cat": "vocare", "answers": ["conj impf 3e-ev pass"] },
	{ "word": "vocaremur", "cat": "vocare", "answers": ["conj impf 1e-mv pass"] },
	{ "word": "vocaremini", "cat": "vocare", "answers": ["conj impf 2e-mv pass"] },
	{ "word": "vocarentur", "cat": "vocare", "answers": ["conj impf 3e-mv pass"] },

	{ "word": "vocaverim", "cat": "vocare", "answers": ["conj perf 1e-ev act"] },
	{ "word": "vocaveris", "cat": "vocare", "answers": ["conj perf 2e-ev act"] },
	{ "word": "vocaverit", "cat": "vocare", "answers": ["conj perf 3e-ev act"] },
	{ "word": "vocaverimus", "cat": "vocare", "answers": ["conj perf 1e-mv act"] },
	{ "word": "vocaveritis", "cat": "vocare", "answers": ["conj perf 2e-mv act"] },
	{ "word": "vocaverint", "cat": "vocare", "answers": ["conj perf 3e-mv act"] },

	{ "word": "vocavissem", "cat": "vocare", "answers": ["conj plqpf 1e-ev act"] },
	{ "word": "vocavisses", "cat": "vocare", "answers": ["conj plqpf 2e-ev act"] },
	{ "word": "vocavisset", "cat": "vocare", "answers": ["conj plqpf 3e-ev act"] },
	{ "word": "vocavissemus", "cat": "vocare", "answers": ["conj plqpf 1e-mv act"] },
	{ "word": "vvocavissetis", "cat": "vocare", "answers": ["conj plqpf 2e-mv act"] },
	{ "word": "vocavissent", "cat": "vocare", "answers": ["conj plqpf 3e-mv act"] },

	{ "word": "voca", "cat": "vocare", "answers": ["imp praes 2e-ev act"] },
	{ "word": "vocate", "cat": "vocare", "answers": ["imp praes 2e-mv act"] },
	{ "word": "vocare", "cat": "vocare", "answers": ["inf praes x act"] },
	{ "word": "vocavisse", "cat": "vocare", "answers": ["inf perf x act"] },
	{ "word": "vocari", "cat": "vocare", "answers": ["inf praes x pass"] },
	{ "word": "vocare", "cat": "vocare", "answers": ["imp 2e-ev pass"] },
	{ "word": "vocamini", "cat": "vocare", "answers": ["imp 2e-mv pass"] },

	{ "word": "vocans", "cat": "vocare", "answers": ["ptc praes x act nom ev m", "ptc praes x act nom ev f", "ptc praes x act nom ev n", "ptc praes x act acc ev n"] },
	{ "word": "vocantis", "cat": "vocare", "answers": ["ptc praes x act gen ev m", "ptc praes x act gen ev f", "ptc praes x act gen ev n"] },
	{ "word": "vocanti", "cat": "vocare", "answers": ["ptc praes x act dat ev m", "ptc praes x act dat ev f", "ptc praes x act dat ev n"] },
	{ "word": "vocante", "cat": "vocare", "answers": ["ptc praes x act abl ev m", "ptc praes x act abl ev f", "ptc praes x act abl ev n"] },
	{ "word": "vocantes", "cat": "vocare", "answers": ["ptc praes x act nom mv m", "ptc praes x act nom mv f"] },
	{ "word": "vocantia", "cat": "vocare", "answers": ["ptc praes x act nom mv n", "ptc praes x act acc mv n"] },
	{ "word": "vocantium", "cat": "vocare", "answers": ["ptc praes x act gen mv m", "ptc praes x act gen mv f", "ptc praes x act gen mv n"] },
	{ "word": "vocantibus", "cat": "vocare", "answers": ["ptc praes x act dat mv m", "ptc praes x act dat mv f", "ptc praes x act dat mv n", "ptc praes x act abl mv m", "ptc praes x act abl mv f", "ptc praes x act abl mv n"] },

	{ "word": "vocatus", "cat": "vocare", "answers": ["ptc perf x pass nom ev m"] },
	{ "word": "vocati", "cat": "vocare", "answers": ["ptc perf x pass gen ev m", "ptc perf x pass nom mv m", "ptc perf x pass gen ev n"] },
	{ "word": "vocato", "cat": "vocare", "answers": ["ptc perf x pass dat ev m", "ptc perf x pass dat ev n", "ptc perf x pass abl ev m", "ptc perf x pass abl ev n",] },
	{ "word": "vocatum", "cat": "vocare", "answers": ["ptc perf x pass acc ev m", "ptc perf x pass nom ev n", "ptc perf x pass acc ev n"] },
	{ "word": "vocatorum", "cat": "vocare", "answers": ["ptc perf x pass gen mv m", "ptc perf x pass gen mv n"] },
	{ "word": "vocatis", "cat": "vocare", "answers": ["ptc perf x pass dat mv m", "ptc perf x pass dat mv f", "ptc perf x pass dat mv n", "ptc perf x pass abl mv m", "ptc perf x abl dat mv f", "ptc perf x pass abl mv n"] },
	{ "word": "vocatos", "cat": "vocare", "answers": ["ptc perf x pass acc mv m"] },
	{ "word": "vocata", "cat": "vocare", "answers": ["ptc perf x pass nom ev f", "ptc perf x pass abl ev f", "ptc perf x pass nom mv n", "ptc perf x pass acc mv n"] },
	{ "word": "vocatae", "cat": "vocare", "answers": ["ptc perf x pass gen ev f", "ptc perf x pass dat ev f", "ptc perf x pass nom mv f"] },
	{ "word": "vocatam", "cat": "vocare", "answers": ["ptc perf x pass acc ev f"] },
	{ "word": "vocatarum", "cat": "vocare", "answers": ["ptc perf x pass gen mv f"] },
	{ "word": "vocatas", "cat": "vocare", "answers": ["ptc perf x pass acc mv f"] },


	{ "word": "teneo", "cat": "tenere", "answers": ["ind praes 1e-ev act"] },
	{ "word": "tenes", "cat": "tenere", "answers": ["ind praes 2e-ev act"] },
	{ "word": "tenet", "cat": "tenere", "answers": ["ind praes 3e-ev act"] },
	{ "word": "tenemus", "cat": "tenere", "answers": ["ind praes 1e-mv act"] },
	{ "word": "tenetis", "cat": "tenere", "answers": ["ind praes 2e-mv act"] },
	{ "word": "tenent", "cat": "tenere", "answers": ["ind praes 3e-mv act"] },
	{ "word": "teneor", "cat": "tenere", "answers": ["ind praes 1e-ev pass"] },
	{ "word": "teneris", "cat": "tenere", "answers": ["ind praes 2e-ev pass"] },
	{ "word": "tenetur", "cat": "tenere", "answers": ["ind praes 3e-ev pass"] },
	{ "word": "tenemur", "cat": "tenere", "answers": ["ind praes 1e-mv pass"] },
	{ "word": "tenemini", "cat": "tenere", "answers": ["ind praes 2e-mv pass"] },
	{ "word": "tenentur", "cat": "tenere", "answers": ["ind praes 3e-mv pass"] },
	{ "word": "tenebam", "cat": "tenere", "answers": ["ind impf 1e-ev act"] },
	{ "word": "tenebas", "cat": "tenere", "answers": ["ind impf 2e-ev act"] },
	{ "word": "tenebat", "cat": "tenere", "answers": ["ind impf 3e-ev act"] },
	{ "word": "tenebamus", "cat": "tenere", "answers": ["ind impf 1e-mv act"] },
	{ "word": "tenebatis", "cat": "tenere", "answers": ["ind impf 2e-mv act"] },
	{ "word": "tenebant", "cat": "tenere", "answers": ["ind impf 3e-mv act"] },
	{ "word": "tenebar", "cat": "tenere", "answers": ["ind impf 1e-ev pass"] },
	{ "word": "tenebaris", "cat": "tenere", "answers": ["ind impf 2e-ev pass"] },
	{ "word": "tenebatur", "cat": "tenere", "answers": ["ind impf 3e-ev pass"] },
	{ "word": "tenebamur", "cat": "tenere", "answers": ["ind impf 1e-mv pass"] },
	{ "word": "tenebamini", "cat": "tenere", "answers": ["ind impf 2e-mv pass"] },
	{ "word": "tenebantur", "cat": "tenere", "answers": ["ind impf 3e-mv pass"] },
	{ "word": "tenebo", "cat": "tenere", "answers": ["ind fut 1e-ev act"] },
	{ "word": "tenebis", "cat": "tenere", "answers": ["ind fut 2e-ev act"] },
	{ "word": "tenebit", "cat": "tenere", "answers": ["ind fut 3e-ev act"] },
	{ "word": "tenebimus", "cat": "tenere", "answers": ["ind fut 1e-mv act"] },
	{ "word": "tenebitis", "cat": "tenere", "answers": ["ind fut 2e-mv act"] },
	{ "word": "tenebunt", "cat": "tenere", "answers": ["ind fut 3e-mv act"] },
	{ "word": "tenebor", "cat": "tenere", "answers": ["ind fut 1e-ev pass"] },
	{ "word": "teneberis", "cat": "tenere", "answers": ["ind fut 2e-ev pass"] },
	{ "word": "tenebitur", "cat": "tenere", "answers": ["ind fut 3e-ev pass"] },
	{ "word": "tenebimur", "cat": "tenere", "answers": ["ind fut 1e-mv pass"] },
	{ "word": "tenebimini", "cat": "tenere", "answers": ["ind fut 2e-mv pass"] },
	{ "word": "tenebuntur", "cat": "tenere", "answers": ["ind fut 3e-mv pass"] },
	{ "word": "tenui", "cat": "tenere", "answers": ["ind perf 1e-ev act"] },
	{ "word": "tenuisti", "cat": "tenere", "answers": ["ind perf 2e-ev act"] },
	{ "word": "tenuit", "cat": "tenere", "answers": ["ind perf 3e-ev act"] },
	{ "word": "tenuimus", "cat": "tenere", "answers": ["ind perf 1e-mv act"] },
	{ "word": "tenuistis", "cat": "tenere", "answers": ["ind perf 2e-mv act"] },
	{ "word": "tenuerunt", "cat": "tenere", "answers": ["ind perf 3e-mv act"] },
	{ "word": "tenueram", "cat": "tenere", "answers": ["ind plqpf 1e-ev act"] },
	{ "word": "tenueras", "cat": "tenere", "answers": ["ind plqpf 2e-ev act"] },
	{ "word": "tenuerat", "cat": "tenere", "answers": ["ind plqpf 3e-ev act"] },
	{ "word": "tenueramus", "cat": "tenere", "answers": ["ind plqpf 1e-mv act"] },
	{ "word": "tenueratis", "cat": "tenere", "answers": ["ind plqpf 2e-mv act"] },
	{ "word": "tenuerant", "cat": "tenere", "answers": ["ind plqpf 3e-mv act"] },
	{ "word": "tenuero", "cat": "tenere", "answers": ["ind fex 1e-ev act"] },
	{ "word": "tenueris", "cat": "tenere", "answers": ["ind fex 2e-ev act"] },
	{ "word": "tenuerit", "cat": "tenere", "answers": ["ind fex 3e-ev act"] },
	{ "word": "tenuerimus", "cat": "tenere", "answers": ["ind fex 1e-mv act"] },
	{ "word": "tenueritis", "cat": "tenere", "answers": ["ind fex 2e-mv act"] },
	{ "word": "tenuerint", "cat": "tenere", "answers": ["ind fex 3e-mv act"] },
	{ "word": "teneam", "cat": "tenere", "answers": ["conj praes 1e-ev act"] },
	{ "word": "teneas", "cat": "tenere", "answers": ["conj praes 2e-ev act"] },
	{ "word": "teneat", "cat": "tenere", "answers": ["conj praes 3e-ev act"] },
	{ "word": "teneamus", "cat": "tenere", "answers": ["conj praes 1e-mv act"] },
	{ "word": "teneatis", "cat": "tenere", "answers": ["conj praes 2e-mv act"] },
	{ "word": "teneant", "cat": "tenere", "answers": ["conj praes 3e-mv act"] },
	{ "word": "tenear", "cat": "tenere", "answers": ["conj praes 1e-ev pass"] },
	{ "word": "tenearis", "cat": "tenere", "answers": ["conj praes 2e-ev pass"] },
	{ "word": "teneatur", "cat": "tenere", "answers": ["conj praes 3e-ev pass"] },
	{ "word": "teneamur", "cat": "tenere", "answers": ["conj praes 1e-mv pass"] },
	{ "word": "teneamini", "cat": "tenere", "answers": ["conj praes 2e-mv pass"] },
	{ "word": "teneantur", "cat": "tenere", "answers": ["conj praes 3e-mv pass"] },
	{ "word": "tenerem", "cat": "tenere", "answers": ["conj impf 1e-ev act"] },
	{ "word": "teneres", "cat": "tenere", "answers": ["conj impf 2e-ev act"] },
	{ "word": "teneret", "cat": "tenere", "answers": ["conj impf 3e-ev act"] },
	{ "word": "teneremus", "cat": "tenere", "answers": ["conj impf 1e-mv act"] },
	{ "word": "teneretis", "cat": "tenere", "answers": ["conj impf 2e-mv act"] },
	{ "word": "tenerent", "cat": "tenere", "answers": ["conj impf 3e-mv act"] },
	{ "word": "tenerer", "cat": "tenere", "answers": ["conj impf 1e-ev pass"] },
	{ "word": "tenereris", "cat": "tenere", "answers": ["conj impf 2e-ev pass"] },
	{ "word": "teneretur", "cat": "tenere", "answers": ["conj impf 3e-ev pass"] },
	{ "word": "teneremur", "cat": "tenere", "answers": ["conj impf 1e-mv pass"] },
	{ "word": "teneremini", "cat": "tenere", "answers": ["conj impf 2e-mv pass"] },
	{ "word": "tenerentur", "cat": "tenere", "answers": ["conj impf 3e-mv pass"] },
	{ "word": "tenuerim", "cat": "tenere", "answers": ["conj perf 1e-ev act"] },
	{ "word": "tenueris", "cat": "tenere", "answers": ["conj perf 2e-ev act"] },
	{ "word": "tenuerit", "cat": "tenere", "answers": ["conj perf 3e-ev act"] },
	{ "word": "tenuerimus", "cat": "tenere", "answers": ["conj perf 1e-mv act"] },
	{ "word": "tenueritis", "cat": "tenere", "answers": ["conj perf 2e-mv act"] },
	{ "word": "tenuerint", "cat": "tenere", "answers": ["conj perf 3e-mv act"] },
	{ "word": "tenere", "cat": "tenere", "answers": ["inf praes x act"] },
	{ "word": "tenuisse", "cat": "tenere", "answers": ["inf perf x act"] },
	{ "word": "teneri", "cat": "tenere", "answers": ["inf praes x pass"] },
	{ "word": "tenere", "cat": "tenere", "answers": ["imp 2e-ev pass"] },
	{ "word": "tenemini", "cat": "tenere", "answers": ["imp 2e-mv pass"] },


	{ "word": "tenens", "cat": "tenere", "answers": ["ptc praes x act nom ev m", "ptc praes x act nom ev f", "ptc praes x act nom ev n", "ptc praes x act acc ev m"] },
	{ "word": "tenentis", "cat": "tenere", "answers": ["ptc praes x act gen ev m", "ptc praes x act gen ev f", "ptc praes x act gen ev n"] },
	{ "word": "tenenti", "cat": "tenere", "answers": ["ptc praes x act dat ev m", "ptc praes x act dat ev f", "ptc praes x act dat ev n"] },
	{ "word": "tenente", "cat": "tenere", "answers": ["ptc praes x act abl ev m", "ptc praes x act abl ev f", "ptc praes x act abl ev n"] },
	{ "word": "tenentes", "cat": "tenere", "answers": ["ptc praes x act nom mv m", "ptc praes x act nom mv f"] },
	{ "word": "tenentia", "cat": "tenere", "answers": ["ptc praes x act nom mv n", "ptc praes x act acc mv n"] },
	{ "word": "tenentium", "cat": "tenere", "answers": ["ptc praes x act gen mv m", "ptc praes x act gen mv f", "ptc praes x act gen mv n"] },
	{ "word": "tenentibus", "cat": "tenere", "answers": ["ptc praes x act dat mv m", "ptc praes x act dat mv f", "ptc praes x act dat mv n", "ptc praes x act abl mv m", "ptc praes x act abl mv f", "ptc praes x act abl mv n"] },

	{ "word": "tentus", "cat": "tenere", "answers": ["ptc perf x pass nom ev m"] },
	{ "word": "tenti", "cat": "tenere", "answers": ["ptc perf x pass gen ev m", "ptc perf x pass nom mv m", "ptc perf x pass gen ev n"] },
	{ "word": "tento", "cat": "tenere", "answers": ["ptc perf x pass dat ev m", "ptc perf x pass dat ev n", "ptc perf x pass abl ev m", "ptc perf x pass abl ev n"] },
	{ "word": "tentum", "cat": "tenere", "answers": ["ptc perf x pass acc ev m", "ptc perf x pass nom ev n", "ptc perf x pass acc ev n"] },
	{ "word": "tentorum", "cat": "tenere", "answers": ["ptc perf x pass gen mv m", "ptc perf x pass gen mv n"] },
	{ "word": "tentis", "cat": "tenere", "answers": ["ptc perf x pass dat mv m", "ptc perf x pass dat mv f", "ptc perf x pass dat mv n", "ptc perf x pass abl mv m", "ptc perf x abl dat mv f", "ptc perf x pass abl mv n"] },
	{ "word": "tentos", "cat": "tenere", "answers": ["ptc perf x pass acc mv m"] },
	{ "word": "tenta", "cat": "tenere", "answers": ["ptc perf x pass nom ev f", "ptc perf x pass abl ev f", "ptc perf x pass nom mv n", "ptc perf x pass acc mv n"] },
	{ "word": "tentae", "cat": "tenere", "answers": ["ptc perf x pass gen ev f", "ptc perf x pass dat ev f", "ptc perf x pass nom mv f"] },
	{ "word": "tentam", "cat": "tenere", "answers": ["ptc perf x pass acc ev f"] },
	{ "word": "tentarum", "cat": "tenere", "answers": ["ptc perf x pass gen mv f"] },
	{ "word": "tentas", "cat": "tenere", "answers": ["ptc perf x pass acc mv f"] },


	{ "word": "audio", "cat": "audire", "answers": ["ind praes 1e-ev act"] },
	{ "word": "audis", "cat": "audire", "answers": ["ind praes 2e-ev act"] },
	{ "word": "audit", "cat": "audire", "answers": ["ind praes 3e-ev act"] },
	{ "word": "audimus", "cat": "audire", "answers": ["ind praes 1e-mv act"] },
	{ "word": "auditis", "cat": "audire", "answers": ["ind praes 2e-mv act"] },
	{ "word": "audiunt", "cat": "audire", "answers": ["ind praes 3e-mv act"] },
	{ "word": "audior", "cat": "audire", "answers": ["ind praes 1e-ev pass"] },
	{ "word": "audiris", "cat": "audire", "answers": ["ind praes 2e-ev pass"] },
	{ "word": "auditur", "cat": "audire", "answers": ["ind praes 3e-ev pass"] },
	{ "word": "audimur", "cat": "audire", "answers": ["ind praes 1e-mv pass"] },
	{ "word": "audimini", "cat": "audire", "answers": ["ind praes 2e-mv pass"] },
	{ "word": "audiuntur", "cat": "audire", "answers": ["ind praes 3e-mv pass"] },
	{ "word": "audiebam", "cat": "audire", "answers": ["ind impf 1e-ev act"] },
	{ "word": "audiebas", "cat": "audire", "answers": ["ind impf 2e-ev act"] },
	{ "word": "audiebat", "cat": "audire", "answers": ["ind impf 3e-ev act"] },
	{ "word": "audiebamus", "cat": "audire", "answers": ["ind impf 1e-mv act"] },
	{ "word": "audiebatis", "cat": "audire", "answers": ["ind impf 2e-mv act"] },
	{ "word": "audiebant", "cat": "audire", "answers": ["ind impf 3e-mv act"] },
	{ "word": "audiebar", "cat": "audire", "answers": ["ind impf 1e-ev pass"] },
	{ "word": "audiebaris", "cat": "audire", "answers": ["ind impf 2e-ev pass"] },
	{ "word": "audiebatur", "cat": "audire", "answers": ["ind impf 3e-ev pass"] },
	{ "word": "audiebamur", "cat": "audire", "answers": ["ind impf 1e-mv pass"] },
	{ "word": "audiebamini", "cat": "audire", "answers": ["ind impf 2e-mv pass"] },
	{ "word": "audiebantur", "cat": "audire", "answers": ["ind impf 3e-mv pass"] },
	{ "word": "audiam", "cat": "audire", "answers": ["ind fut 1e-ev act"] },
	{ "word": "audies", "cat": "audire", "answers": ["ind fut 2e-ev act"] },
	{ "word": "audiet", "cat": "audire", "answers": ["ind fut 3e-ev act"] },
	{ "word": "audiemus", "cat": "audire", "answers": ["ind fut 1e-mv act"] },
	{ "word": "audietis", "cat": "audire", "answers": ["ind fut 2e-mv act"] },
	{ "word": "audient", "cat": "audire", "answers": ["ind fut 3e-mv act"] },
	{ "word": "audiar", "cat": "audire", "answers": ["ind fut 1e-ev pass"] },
	{ "word": "audieris", "cat": "audire", "answers": ["ind fut 2e-ev pass"] },
	{ "word": "audietur", "cat": "audire", "answers": ["ind fut 3e-ev pass"] },
	{ "word": "audiemur", "cat": "audire", "answers": ["ind fut 1e-mv pass"] },
	{ "word": "audiemini", "cat": "audire", "answers": ["ind fut 2e-mv pass"] },
	{ "word": "audientur", "cat": "audire", "answers": ["ind fut 3e-mv pass"] },
	{ "word": "audivi", "cat": "audire", "answers": ["ind perf 1e-ev act"] },
	{ "word": "audivisti", "cat": "audire", "answers": ["ind perf 2e-ev act"] },
	{ "word": "audivit", "cat": "audire", "answers": ["ind perf 3e-ev act"] },
	{ "word": "audivimus", "cat": "audire", "answers": ["ind perf 1e-mv act"] },
	{ "word": "audivistis", "cat": "audire", "answers": ["ind perf 2e-mv act"] },
	{ "word": "audiverunt", "cat": "audire", "answers": ["ind perf 3e-mv act"] },
	{ "word": "audiveram", "cat": "audire", "answers": ["ind plqpf 1e-ev act"] },
	{ "word": "audiveras", "cat": "audire", "answers": ["ind plqpf 2e-ev act"] },
	{ "word": "audiverat", "cat": "audire", "answers": ["ind plqpf 3e-ev act"] },
	{ "word": "audiveramus", "cat": "audire", "answers": ["ind plqpf 1e-mv act"] },
	{ "word": "audiveratis", "cat": "audire", "answers": ["ind plqpf 2e-mv act"] },
	{ "word": "audiverant", "cat": "audire", "answers": ["ind plqpf 3e-mv act"] },
	{ "word": "audivero", "cat": "audire", "answers": ["ind fex 1e-ev act"] },
	{ "word": "audiveris", "cat": "audire", "answers": ["ind fex 2e-ev act"] },
	{ "word": "audiverit", "cat": "audire", "answers": ["ind fex 3e-ev act"] },
	{ "word": "audiverimus", "cat": "audire", "answers": ["ind fex 1e-mv act"] },
	{ "word": "audiveritis", "cat": "audire", "answers": ["ind fex 2e-mv act"] },
	{ "word": "audiverint", "cat": "audire", "answers": ["ind fex 3e-mv act"] },
	{ "word": "audiam", "cat": "audire", "answers": ["conj praes 1e-ev act"] },
	{ "word": "audias", "cat": "audire", "answers": ["conj praes 2e-ev act"] },
	{ "word": "audiat", "cat": "audire", "answers": ["conj praes 3e-ev act"] },
	{ "word": "audiamus", "cat": "audire", "answers": ["conj praes 1e-mv act"] },
	{ "word": "audiatis", "cat": "audire", "answers": ["conj praes 2e-mv act"] },
	{ "word": "audiant", "cat": "audire", "answers": ["conj praes 3e-mv act"] },
	{ "word": "audiar", "cat": "audire", "answers": ["conj praes 1e-ev pass"] },
	{ "word": "audiaris", "cat": "audire", "answers": ["conj praes 2e-ev pass"] },
	{ "word": "audiatur", "cat": "audire", "answers": ["conj praes 3e-ev pass"] },
	{ "word": "audiamur", "cat": "audire", "answers": ["conj praes 1e-mv pass"] },
	{ "word": "audiamini", "cat": "audire", "answers": ["conj praes 2e-mv pass"] },
	{ "word": "audiantur", "cat": "audire", "answers": ["conj praes 3e-mv pass"] },
	{ "word": "audirem", "cat": "audire", "answers": ["conj impf 1e-ev act"] },
	{ "word": "audires", "cat": "audire", "answers": ["conj impf 2e-ev act"] },
	{ "word": "audiret", "cat": "audire", "answers": ["conj impf 3e-ev act"] },
	{ "word": "audiremus", "cat": "audire", "answers": ["conj impf 1e-mv act"] },
	{ "word": "audiretis", "cat": "audire", "answers": ["conj impf 2e-mv act"] },
	{ "word": "audirent", "cat": "audire", "answers": ["conj impf 3e-mv act"] },
	{ "word": "audirer", "cat": "audire", "answers": ["conj impf 1e-ev pass"] },
	{ "word": "audireris", "cat": "audire", "answers": ["conj impf 2e-ev pass"] },
	{ "word": "audiretur", "cat": "audire", "answers": ["conj impf 3e-ev pass"] },
	{ "word": "audiremur", "cat": "audire", "answers": ["conj impf 1e-mv pass"] },
	{ "word": "audiremini", "cat": "audire", "answers": ["conj impf 2e-mv pass"] },
	{ "word": "audirentur", "cat": "audire", "answers": ["conj impf 3e-mv pass"] },
	{ "word": "audiverim", "cat": "audire", "answers": ["conj perf 1e-ev act"] },
	{ "word": "audiveris", "cat": "audire", "answers": ["conj perf 2e-ev act"] },
	{ "word": "audiverit", "cat": "audire", "answers": ["conj perf 3e-ev act"] },
	{ "word": "audiverimus", "cat": "audire", "answers": ["conj perf 1e-mv act"] },
	{ "word": "audiveritis", "cat": "audire", "answers": ["conj perf 2e-mv act"] },
	{ "word": "audiverint", "cat": "audire", "answers": ["conj perf 3e-mv act"] },
	{ "word": "audi", "cat": "audire", "answers": ["imp praes 2e-ev act"] },
	{ "word": "audite", "cat": "audire", "answers": ["imp praes 2e-mv act"] },
	{ "word": "audire", "cat": "audire", "answers": ["inf praes x act"] },
	{ "word": "audivisse", "cat": "audire", "answers": ["inf perf x act"] },
	{ "word": "audiri", "cat": "audire", "answers": ["inf praes x pass"] },
	{ "word": "audire", "cat": "audire", "answers": ["imp 2e-ev pass"] },
	{ "word": "audimini", "cat": "audire", "answers": ["imp 2e-mv pass"] },


	{ "word": "auditus", "cat": "audire", "answers": ["ptc perf x pass nom ev m"] },
	{ "word": "auditi", "cat": "audire", "answers": ["ptc perf x pass gen ev m", "ptc perf x pass nom mv m", "ptc perf x pass gen ev n"] },
	{ "word": "audito", "cat": "audire", "answers": ["ptc perf x pass dat ev m", "ptc perf x pass dat ev n", "ptc perf x pass abl ev m", "ptc perf x pass abl ev n"] },
	{ "word": "auditum", "cat": "audire", "answers": ["ptc perf x pass acc ev m", "ptc perf x pass nom ev n", "ptc perf x pass acc ev n"] },
	{ "word": "auditorum", "cat": "audire", "answers": ["ptc perf x pass gen mv m", "ptc perf x pass gen mv n"] },
	{ "word": "auditis", "cat": "audire", "answers": ["ptc perf x pass dat mv m", "ptc perf x pass dat mv f", "ptc perf x pass dat mv n", "ptc perf x pass abl mv m", "ptc perf x abl dat mv f", "ptc perf x pass abl mv n"] },
	{ "word": "auditos", "cat": "audire", "answers": ["ptc perf x pass acc mv m"] },
	{ "word": "audita", "cat": "audire", "answers": ["ptc perf x pass nom ev f", "ptc perf x pass abl ev f", "ptc perf x pass nom mv n", "ptc perf x pass acc mv n"] },
	{ "word": "auditae", "cat": "audire", "answers": ["ptc perf x pass gen ev f", "ptc perf x pass dat ev f", "ptc perf x pass nom mv f"] },
	{ "word": "auditam", "cat": "audire", "answers": ["ptc perf x pass acc ev f"] },
	{ "word": "auditarum", "cat": "audire", "answers": ["ptc perf x pass gen mv f"] },
	{ "word": "auditas", "cat": "audire", "answers": ["ptc perf x pass acc mv f"] },




	{ "word": "mitto", "cat": "mittere", "answers": ["ind praes 1e-ev act"] },
	{ "word": "mittis", "cat": "mittere", "answers": ["ind praes 2e-ev act"] },
	{ "word": "mittit", "cat": "mittere", "answers": ["ind praes 3e-ev act"] },
	{ "word": "mittimus", "cat": "mittere", "answers": ["ind praes 1e-mv act"] },
	{ "word": "mittitis", "cat": "mittere", "answers": ["ind praes 2e-mv act"] },
	{ "word": "mittunt", "cat": "mittere", "answers": ["ind praes 3e-mv act"] },
	{ "word": "mittor", "cat": "mittere", "answers": ["ind praes 1e-ev pass"] },
	{ "word": "mitteris", "cat": "mittere", "answers": ["ind praes 2e-ev pass"] },
	{ "word": "mittitur", "cat": "mittere", "answers": ["ind praes 3e-ev pass"] },
	{ "word": "mittimur", "cat": "mittere", "answers": ["ind praes 1e-mv pass"] },
	{ "word": "mittimini", "cat": "mittere", "answers": ["ind praes 2e-mv pass"] },
	{ "word": "mittuntur", "cat": "mittere", "answers": ["ind praes 3e-mv pass"] },
	{ "word": "mittebam", "cat": "mittere", "answers": ["ind impf 1e-ev act"] },
	{ "word": "mittebas", "cat": "mittere", "answers": ["ind impf 2e-ev act"] },
	{ "word": "mittebat", "cat": "mittere", "answers": ["ind impf 3e-ev act"] },
	{ "word": "mittebamus", "cat": "mittere", "answers": ["ind impf 1e-mv act"] },
	{ "word": "mittebatis", "cat": "mittere", "answers": ["ind impf 2e-mv act"] },
	{ "word": "mittebant", "cat": "mittere", "answers": ["ind impf 3e-mv act"] },
	{ "word": "mittebar", "cat": "mittere", "answers": ["ind impf 1e-ev pass"] },
	{ "word": "mittebaris", "cat": "mittere", "answers": ["ind impf 2e-ev pass"] },
	{ "word": "mittebatur", "cat": "mittere", "answers": ["ind impf 3e-ev pass"] },
	{ "word": "mittebamur", "cat": "mittere", "answers": ["ind impf 1e-mv pass"] },
	{ "word": "mittebamini", "cat": "mittere", "answers": ["ind impf 2e-mv pass"] },
	{ "word": "mittebantur", "cat": "mittere", "answers": ["ind impf 3e-mv pass"] },
	{ "word": "mittam", "cat": "mittere", "answers": ["ind fut 1e-ev act"] },
	{ "word": "mittes", "cat": "mittere", "answers": ["ind fut 2e-ev act"] },
	{ "word": "mittet", "cat": "mittere", "answers": ["ind fut 3e-ev act"] },
	{ "word": "mittemus", "cat": "mittere", "answers": ["ind fut 1e-mv act"] },
	{ "word": "mittetis", "cat": "mittere", "answers": ["ind fut 2e-mv act"] },
	{ "word": "mittent", "cat": "mittere", "answers": ["ind fut 3e-mv act"] },
	{ "word": "mittar", "cat": "mittere", "answers": ["ind fut 1e-ev pass"] },
	{ "word": "mitteris", "cat": "mittere", "answers": ["ind fut 2e-ev pass"] },
	{ "word": "mittetur", "cat": "mittere", "answers": ["ind fut 3e-ev pass"] },
	{ "word": "mittemur", "cat": "mittere", "answers": ["ind fut 1e-mv pass"] },
	{ "word": "mittemini", "cat": "mittere", "answers": ["ind fut 2e-mv pass"] },
	{ "word": "mittentur", "cat": "mittere", "answers": ["ind fut 3e-mv pass"] },
	{ "word": "misi", "cat": "mittere", "answers": ["ind perf 1e-ev act"] },
	{ "word": "misisti", "cat": "mittere", "answers": ["ind perf 2e-ev act"] },
	{ "word": "misit", "cat": "mittere", "answers": ["ind perf 3e-ev act"] },
	{ "word": "misimus", "cat": "mittere", "answers": ["ind perf 1e-mv act"] },
	{ "word": "misistis", "cat": "mittere", "answers": ["ind perf 2e-mv act"] },
	{ "word": "miserunt", "cat": "mittere", "answers": ["ind perf 3e-mv act"] },
	{ "word": "miseram", "cat": "mittere", "answers": ["ind plqpf 1e-ev act"] },
	{ "word": "miseras", "cat": "mittere", "answers": ["ind plqpf 2e-ev act"] },
	{ "word": "miserat", "cat": "mittere", "answers": ["ind plqpf 3e-ev act"] },
	{ "word": "miseramus", "cat": "mittere", "answers": ["ind plqpf 1e-mv act"] },
	{ "word": "miserais", "cat": "mittere", "answers": ["ind plqpf 2e-mv act"] },
	{ "word": "miserant", "cat": "mittere", "answers": ["ind plqpf 3e-mv act"] },
	{ "word": "miseram", "cat": "mittere", "answers": ["ind fex 1e-ev act"] },
	{ "word": "miseras", "cat": "mittere", "answers": ["ind fex 2e-ev act"] },
	{ "word": "miserat", "cat": "mittere", "answers": ["ind fex 3e-ev act"] },
	{ "word": "miseramus", "cat": "mittere", "answers": ["ind fex 1e-mv act"] },
	{ "word": "miserais", "cat": "mittere", "answers": ["ind fex 2e-mv act"] },
	{ "word": "miserant", "cat": "mittere", "answers": ["ind fex 3e-mv act"] },
	{ "word": "mitte", "cat": "mittere", "answers": ["imp praes 2e-ev act"] },
	{ "word": "mittite", "cat": "mittere", "answers": ["imp praes 2e-mv act"] },
	{ "word": "mittere", "cat": "mittere", "answers": ["inf praes x act"] },
	{ "word": "misisse", "cat": "mittere", "answers": ["inf perf x act"] },
	{ "word": "mitti", "cat": "mittere", "answers": ["inf praes x pass"] },
	{ "word": "mittere", "cat": "mittere", "answers": ["imp 2e-ev pass"] },
	{ "word": "mittimini", "cat": "mittere", "answers": ["imp 2e-mv pass"] },


	{ "word": "missus", "cat": "mittere", "answers": ["ptc perf x pass nom ev m"] },
	{ "word": "missi", "cat": "mittere", "answers": ["ptc perf x pass gen ev m", "ptc perf x pass nom mv m", "ptc perf x pass gen ev n"] },
	{ "word": "misso", "cat": "mittere", "answers": ["ptc perf x pass dat ev m", "ptc perf x pass dat ev n", "ptc perf x pass abl ev m", "ptc perf x pass abl ev n"] },
	{ "word": "missum", "cat": "mittere", "answers": ["ptc perf x pass acc ev m", "ptc perf x pass nom ev n", "ptc perf x pass acc ev n"] },
	{ "word": "missorum", "cat": "mittere", "answers": ["ptc perf x pass gen mv m", "ptc perf x pass gen mv n"] },
	{ "word": "missis", "cat": "mittere", "answers": ["ptc perf x pass dat mv m", "ptc perf x pass dat mv f", "ptc perf x pass dat mv n", "ptc perf x pass abl mv m", "ptc perf x abl dat mv f", "ptc perf x pass abl mv n"] },
	{ "word": "missos", "cat": "mittere", "answers": ["ptc perf x pass acc mv m"] },
	{ "word": "missa", "cat": "mittere", "answers": ["ptc perf x pass nom ev f", "ptc perf x pass abl ev f", "ptc perf x pass nom mv n", "ptc perf x pass nom mv n"] },
	{ "word": "missae", "cat": "mittere", "answers": ["ptc perf x pass gen ev f", "ptc perf x pass dat ev f", "ptc perf x pass nom mv f"] },
	{ "word": "missam", "cat": "mittere", "answers": ["ptc perf x pass acc ev f"] },
	{ "word": "missarum", "cat": "mittere", "answers": ["ptc perf x pass gen mv f"] },
	{ "word": "missas", "cat": "mittere", "answers": ["ptc perf x pass acc mv f"] },




	{ "word": "sum", "cat": "esse", "answers": ["ind praes 1e-ev act"] },
	{ "word": "es", "cat": "esse", "answers": ["ind praes 2e-ev act"] },
	{ "word": "est", "cat": "esse", "answers": ["ind praes 3e-ev act"] },
	{ "word": "sumus", "cat": "esse", "answers": ["ind praes 1e-mv act"] },
	{ "word": "estis", "cat": "esse", "answers": ["ind praes 2e-mv act"] },
	{ "word": "sunt", "cat": "esse", "answers": ["ind praes 3e-mv act"] },

	{ "word": "eram", "cat": "esse", "answers": ["ind impf 1e-ev act"] },
	{ "word": "eras", "cat": "esse", "answers": ["ind impf 2e-ev act"] },
	{ "word": "erat", "cat": "esse", "answers": ["ind impf 3e-ev act"] },
	{ "word": "eramus", "cat": "esse", "answers": ["ind impf 1e-mv act"] },
	{ "word": "eratis", "cat": "esse", "answers": ["ind impf 2e-mv act"] },
	{ "word": "erant", "cat": "esse", "answers": ["ind impf 3e-mv act"] },

	{ "word": "ero", "cat": "esse", "answers": ["ind fut 1e-ev act"] },
	{ "word": "eris", "cat": "esse", "answers": ["ind fut 2e-ev act"] },
	{ "word": "erit", "cat": "esse", "answers": ["ind fut 3e-ev act"] },
	{ "word": "erimus", "cat": "esse", "answers": ["ind fut 1e-mv act"] },
	{ "word": "eritis", "cat": "esse", "answers": ["ind fut 2e-mv act"] },
	{ "word": "erunt", "cat": "esse", "answers": ["ind fut 3e-mv act"] },

	{ "word": "fui", "cat": "esse", "answers": ["ind perf 1e-ev act"] },
	{ "word": "fuisti", "cat": "esse", "answers": ["ind perf 2e-ev act"] },
	{ "word": "fuit", "cat": "esse", "answers": ["ind perf 3e-ev act"] },
	{ "word": "fuimus", "cat": "esse", "answers": ["ind perf 1e-mv act"] },
	{ "word": "fuistis", "cat": "esse", "answers": ["ind perf 2e-mv act"] },
	{ "word": "fuerunt", "cat": "esse", "answers": ["ind perf 3e-mv act"] },
	{ "word": "fueram", "cat": "esse", "answers": ["ind plqpf 1e-ev act"] },
	{ "word": "fueras", "cat": "esse", "answers": ["ind plqpf 2e-ev act"] },
	{ "word": "fuerat", "cat": "esse", "answers": ["ind plqpf 3e-ev act"] },
	{ "word": "fueramus", "cat": "esse", "answers": ["ind plqpf 1e-mv act"] },
	{ "word": "fueratis", "cat": "esse", "answers": ["ind plqpf 2e-mv act"] },
	{ "word": "fuerant", "cat": "esse", "answers": ["ind plqpf 3e-mv act"] },
	{ "word": "fuero", "cat": "esse", "answers": ["ind fex 1e-ev act"] },
	{ "word": "fueris", "cat": "esse", "answers": ["ind fex 2e-ev act"] },
	{ "word": "fuerit", "cat": "esse", "answers": ["ind fex 3e-ev act"] },
	{ "word": "fuerimus", "cat": "esse", "answers": ["ind fex 1e-mv act"] },
	{ "word": "fueritis", "cat": "esse", "answers": ["ind fex 2e-mv act"] },
	{ "word": "fuerint", "cat": "esse", "answers": ["ind fex 3e-mv act"] },
	{ "word": "sim", "cat": "esse", "answers": ["conj praes 1e-ev act"] },
	{ "word": "sis", "cat": "esse", "answers": ["conj praes 2e-ev act"] },
	{ "word": "sit", "cat": "esse", "answers": ["conj praes 3e-ev act"] },
	{ "word": "simus", "cat": "esse", "answers": ["conj praes 1e-mv act"] },
	{ "word": "sitis", "cat": "esse", "answers": ["conj praes 2e-mv act"] },
	{ "word": "sint", "cat": "esse", "answers": ["conj praes 3e-mv act"] },

	{ "word": "essem", "cat": "esse", "answers": ["conj impf 1e-ev act"] },
	{ "word": "esses", "cat": "esse", "answers": ["conj impf 2e-ev act"] },
	{ "word": "esset", "cat": "esse", "answers": ["conj impf 3e-ev act"] },
	{ "word": "essemus", "cat": "esse", "answers": ["conj impf 1e-mv act"] },
	{ "word": "essetis", "cat": "esse", "answers": ["conj impf 2e-mv act"] },
	{ "word": "essent", "cat": "esse", "answers": ["conj impf 3e-mv act"] },
	{ "word": "fuerim", "cat": "esse", "answers": ["conj perf 1e-ev act"] },
	{ "word": "fueris", "cat": "esse", "answers": ["conj perf 2e-ev act"] },
	{ "word": "fuerit", "cat": "esse", "answers": ["conj perf 3e-ev act"] },
	{ "word": "fuerimus", "cat": "esse", "answers": ["conj perf 1e-mv act"] },
	{ "word": "fueritis", "cat": "esse", "answers": ["conj perf 2e-mv act"] },
	{ "word": "fuerint", "cat": "esse", "answers": ["conj perf 3e-mv act"] },

	{ "word": "fuissem", "cat": "esse", "answers": ["conj plqpf 1e-ev act"] },
	{ "word": "fuisses", "cat": "esse", "answers": ["conj plqpf 2e-ev act"] },
	{ "word": "fuisset", "cat": "esse", "answers": ["conj plqpf 3e-ev act"] },
	{ "word": "fuissemus", "cat": "esse", "answers": ["conj plqpf 1e-mv act"] },
	{ "word": "fuissetis", "cat": "esse", "answers": ["conj plqpf 2e-mv act"] },
	{ "word": "fuissent", "cat": "esse", "answers": ["conj plqpf 3e-mv act"] },
	{ "word": "esse", "cat": "esse", "answers": ["inf praes x act"] },
	{ "word": "es", "cat": "esse", "answers": ["imp praes 2e-ev act"] },
	{ "word": "este", "cat": "esse", "answers": ["imp praes 2e-mv act"] },
	{ "word": "fuisse", "cat": "esse", "answers": ["inf perf x act"] }




];

export const qLatinNoun= [
	{ "word": "mensa", "cat": "mensa", "answers": ["nom ev f", "abl ev f"] },
	{ "word": "mensae", "cat": "mensa", "answers": ["gen ev f", "dat ev f", "nom mv f"] },
	{ "word": "mensam", "cat": "mensa", "answers": ["acc ev f"] },
	{ "word": "mensarum", "cat": "mensa", "answers": ["gen mv f"] },
	{ "word": "mensis", "cat": "mensa", "answers": ["dat mv f", "abl mv f"] },
	{ "word": "mensas", "cat": "mensa", "answers": ["acc mv f"] },

	{ "word": "servus", "cat": "servus", "answers": ["nom ev m"] },
	{ "word": "servi", "cat": "servus", "answers": ["gen ev m", "nom mv m"] },
	{ "word": "servo", "cat": "servus", "answers": ["dat ev m", "abl ev m"] },
	{ "word": "servum", "cat": "servus", "answers": ["acc ev m"] },
	{ "word": "servorum", "cat": "servus", "answers": ["gen mv m"] },
	{ "word": "servis", "cat": "servus", "answers": ["dat mv m", "abl mv m"] },
	{ "word": "servos", "cat": "servus", "answers": ["acc mv m"] },

	{ "word": "donum", "cat": "donum", "answers": ["nom ev n", "acc ev n"] },
	{ "word": "doni", "cat": "donum", "answers": ["gen ev n"] },
	{ "word": "dono", "cat": "donum", "answers": ["dat ev n", "abl ev n"] },
	{ "word": "dona", "cat": "donum", "answers": ["nom mv n", "acc mv n"] },
	{ "word": "donorum", "cat": "donum", "answers": ["gen mv n"] },
	{ "word": "donis", "cat": "donum", "answers": ["dat mv n", "abl mv n"] },

	{ "word": "rex", "cat": "rex", "answers": ["nom ev m"] },
	{ "word": "regis", "cat": "rex", "answers": ["gen ev m"] },
	{ "word": "regi", "cat": "rex", "answers": ["dat ev m"] },
	{ "word": "regem", "cat": "rex", "answers": ["acc ev m"] },
	{ "word": "rege", "cat": "rex", "answers": ["abl ev m"] },
	{ "word": "reges", "cat": "rex", "answers": ["nom mv m", "acc mv m"] },
	{ "word": "regum", "cat": "rex", "answers": ["gen mv m"] },
	{ "word": "regibus", "cat": "rex", "answers": ["dat mv m", "abl mv m"] },

	{ "word": "nomen", "cat": "nomen", "answers": ["nom ev n", "acc ev n"] },
	{ "word": "nominis", "cat": "nomen", "answers": ["gen ev n"] },
	{ "word": "nomini", "cat": "nomen", "answers": ["dat ev n"] },
	{ "word": "nomine", "cat": "nomen", "answers": ["abl ev n"] },
	{ "word": "nomina", "cat": "nomen", "answers": ["nom mv n", "acc mv n"] },
	{ "word": "nominum", "cat": "nomen", "answers": ["gen mv n"] },
	{ "word": "nominbus", "cat": "nomen", "answers": ["dat mv n", "abl mv n"] },

	{ "word": "bona", "cat": "bonus", "answers": ["nom ev f", "abl ev f", "nom mv n", "acc mv n"] },
	{ "word": "bonae", "cat": "bonus", "answers": ["gen ev f", "dat ev f", "nom mv f"] },
	{ "word": "bonam", "cat": "bonus", "answers": ["acc ev f"] },
	{ "word": "bonarum", "cat": "bonus", "answers": ["gen mv f"] },
	{ "word": "bonis", "cat": "bonus", "answers": ["dat mv f", "abl mv f", "dat mv m", "abl mv m", "dat mv n", "abl mv n"] },
	{ "word": "bonas", "cat": "bonus", "answers": ["acc mv f"] },

	{ "word": "bonus", "cat": "bonus", "answers": ["nom ev m"] },
	{ "word": "boni", "cat": "bonus", "answers": ["gen ev m", "nom mv m", "gen ev n"] },
	{ "word": "bono", "cat": "bonus", "answers": ["dat ev m", "abl ev m", "dat ev n", "abl ev n"] },
	{ "word": "bonum", "cat": "bonus", "answers": ["acc ev m", "nom ev n", "acc ev n"] },
	{ "word": "bonorum", "cat": "bonus", "answers": ["gen mv m", "gen mv n"] },
	{ "word": "bonos", "cat": "bonus", "answers": ["acc mv m"] },

	{ "word": "fortis", "cat": "fortis", "answers": ["nom ev m", "nom ev f", "gen ev m", "gen ev f", "gen ev n"] },
	{ "word": "forti", "cat": "fortis", "answers": ["dat ev m", "dat ev f", "dat ev n", "abl ev m", "abl ev f", "abl ev n"] },
	{ "word": "fortem", "cat": "fortis", "answers": ["acc ev m", "acc ev f"] },
	{ "word": "fortes", "cat": "fortis", "answers": ["nom mv m", "nom mv f", "acc mv m", "acc mv f"] },
	{ "word": "fortium", "cat": "fortis", "answers": ["gen mv m", "gen mv f", "gen mv n"] },
	{ "word": "fortibus", "cat": "fortis", "answers": ["dat mv m", "abl mv m", "dat mv f", "abl mv f", "dat mv n", "abl mv n"] },
	{ "word": "forte", "cat": "fortis", "answers": ["nom ev n", "acc ev n"] },
	{ "word": "fortia", "cat": "fortis", "answers": ["nom mv n", "acc mv n"] },

	{ "word": "ingens", "cat": "ingens", "answers": ["nom ev m", "nom ev f", "nom ev n", "acc ev n"] },
	{ "word": "ingentis", "cat": "ingens", "answers": ["gen ev m", "gen ev f", "gen ev n"] },
	{ "word": "ingenti", "cat": "ingens", "answers": ["dat ev m", "dat ev f", "dat ev n", "abl ev m", "abl ev f", "abl ev n"] },
	{ "word": "ingentem", "cat": "ingens", "answers": ["acc ev m", "acc ev f"] },
	{ "word": "ingentes", "cat": "ingens", "answers": ["nom mv m", "nom mv f", "acc mv m", "acc mv f"] },
	{ "word": "ingentium", "cat": "ingens", "answers": ["gen mv m", "gen mv f", "gen mv n"] },
	{ "word": "ingentibus", "cat": "ingens", "answers": ["dat mv m", "abl mv m", "dat mv f", "abl mv f", "dat mv n", "abl mv n"] },
	{ "word": "ingentia", "cat": "ingens", "answers": ["nom mv n", "acc mv n"] },

];

export const qGreekNoun = [
	{ "word": "ὁ", "cat": "lidwoord", "answers": ["nom ev m"] },
	{ "word": "τοῦ", "cat": "lidwoord", "answers": ["gen ev m", "gen ev n"] },
	{ "word": "τῷ", "cat": "lidwoord", "answers": ["dat ev m", "dat ev n"] },
	{ "word": "τόν", "cat": "lidwoord", "answers": ["acc ev m"] },
	{ "word": "οἱ", "cat": "lidwoord", "answers": ["nom mv m"] },
	{ "word": "τῶν", "cat": "lidwoord", "answers": ["gen mv m", "gen mv f", "gen mv n"] },
	{ "word": "τοῖς", "cat": "lidwoord", "answers": ["dat mv m", "dat mv n"] },
	{ "word": "τούς", "cat": "lidwoord", "answers": ["acc mv m"] },
	{ "word": "ἡ", "cat": "lidwoord", "answers": ["nom ev f"] },
	{ "word": "τῆς", "cat": "lidwoord", "answers": ["gen ev f"] },
	{ "word": "τῇ", "cat": "lidwoord", "answers": ["dat ev f"] },
	{ "word": "τήν", "cat": "lidwoord", "answers": ["acc ev f"] },
	{ "word": "αἱ", "cat": "lidwoord", "answers": ["nom mv f"] },
	{ "word": "ταῖς", "cat": "lidwoord", "answers": ["dat mv f"] },
	{ "word": "τάς", "cat": "lidwoord", "answers": ["acc mv f"] },
	{ "word": "τό", "cat": "lidwoord", "answers": ["nom ev n", "acc ev n"] },
	{ "word": "τά", "cat": "lidwoord", "answers": ["nom mv n", "acc mv n"] },
	{ "word": "μάχη", "cat": "μάχη", "answers": ["nom ev f"] },
	{ "word": "μάχης", "cat": "μάχη", "answers": ["gen ev f"] },
	{ "word": "μάχῃ", "cat": "μάχη", "answers": ["dat ev f"] },
	{ "word": "μάχην", "cat": "μάχη", "answers": ["acc ev f"] },
	{ "word": "μάχαι", "cat": "μάχη", "answers": ["nom mv f"] },
	{ "word": "μαχῶν", "cat": "μάχη", "answers": ["gen mv f"] },
	{ "word": "μάχαις", "cat": "μάχη", "answers": ["dat mv f"] },
	{ "word": "μάχας", "cat": "μάχη", "answers": ["acc mv f"] },
	{ "word": "χώρα", "cat": "χώρα", "answers": ["nom ev f"] },
	{ "word": "χώρας", "cat": "χώρα", "answers": ["gen ev f", "acc mv f"] },
	{ "word": "χώρᾳ", "cat": "χώρα", "answers": ["dat ev f"] },
	{ "word": "χώραν", "cat": "χώρα", "answers": ["acc ev f"] },
	{ "word": "χῶραι", "cat": "χώρα", "answers": ["nom mv f"] },
	{ "word": "χωρῶν", "cat": "χώρα", "answers": ["gen mv f"] },
	{ "word": "χώραις", "cat": "χώρα", "answers": ["dat mv f"] },
	{ "word": "θάλαττα", "cat": "θάλαττα", "answers": ["nom ev f"] },
	{ "word": "θαλάττης", "cat": "θάλαττα", "answers": ["gen ev f"] },
	{ "word": "θαλάττῃ", "cat": "θάλαττα", "answers": ["dat ev f"] },
	{ "word": "θάλατταν", "cat": "θάλαττα", "answers": ["acc ev f"] },
	{ "word": "θάλατται", "cat": "θάλαττα", "answers": ["nom mv f"] },
	{ "word": "θαλαττῶν", "cat": "θάλαττα", "answers": ["gen mv f"] },
	{ "word": "θαλάτταις", "cat": "θάλαττα", "answers": ["dat mv f"] },
	{ "word": "θαλάττας", "cat": "θάλαττα", "answers": ["acc mv f"] },
	{ "word": "δεσπότης", "cat": "δεσπότης", "answers": ["nom ev m"] },
	{ "word": "δεσπότου", "cat": "δεσπότης", "answers": ["gen ev m"] },
	{ "word": "δεσπότῃ", "cat": "δεσπότης", "answers": ["dat ev m"] },
	{ "word": "δεσπότην", "cat": "δεσπότης", "answers": ["acc ev m"] },
	{ "word": "δεσπόται", "cat": "δεσπότης", "answers": ["nom mv m"] },
	{ "word": "δεσποτῶν", "cat": "δεσπότης", "answers": ["gen mv m"] },
	{ "word": "δεσπόταις", "cat": "δεσπότης", "answers": ["dat mv m"] },
	{ "word": "δεσπότας", "cat": "δεσπότης", "answers": ["acc mv m"] },
	{ "word": "δοῦλος", "cat": "δοῦλος", "answers": ["nom ev m"] },
	{ "word": "δούλου", "cat": "δοῦλος", "answers": ["gen ev m"] },
	{ "word": "δούλῳ", "cat": "δοῦλος", "answers": ["dat ev m"] },
	{ "word": "δοῦλον", "cat": "δοῦλος", "answers": ["acc ev m"] },
	{ "word": "δοῦλοι", "cat": "δοῦλος", "answers": ["nom mv m"] },
	{ "word": "δούλων", "cat": "δοῦλος", "answers": ["gen mv m"] },
	{ "word": "δούλοις", "cat": "δοῦλος", "answers": ["dat mv m"] },
	{ "word": "δούλους", "cat": "δοῦλος", "answers": ["acc mv m"] },
	{ "word": "θηρίον", "cat": "θηρίον", "answers": ["nom ev n", "acc ev n"] },
	{ "word": "θηρίου", "cat": "θηρίον", "answers": ["gen ev n"] },
	{ "word": "θηρίῳ", "cat": "θηρίον", "answers": ["dat ev n"] },
	{ "word": "θηρία", "cat": "θηρίον", "answers": ["nom mv n", "acc mv n"] },
	{ "word": "θηρίων", "cat": "θηρίον", "answers": ["gen mv n"] },
	{ "word": "θηρίοις", "cat": "θηρίον", "answers": ["dat mv n"] },
	{ "word": "σωτήρ", "cat": "σωτήρ", "answers": ["nom ev m"] },
	{ "word": "σωτῆρος", "cat": "σωτήρ", "answers": ["gen ev m"] },
	{ "word": "σωτῆρι", "cat": "σωτήρ", "answers": ["dat ev m"] },
	{ "word": "σωτῆρα", "cat": "σωτήρ", "answers": ["acc ev m"] },
	{ "word": "σωτῆρες", "cat": "σωτήρ", "answers": ["nom mv m"] },
	{ "word": "σωτήρων", "cat": "σωτήρ", "answers": ["gen mv m"] },
	{ "word": "σωτῆρσι(ν)", "cat": "σωτήρ", "answers": ["dat mv m"] },
	{ "word": "σωτῆρα", "cat": "σωτήρ", "answers": ["acc mv m"] },
	{ "word": "γυνή", "cat": "γυνή", "answers": ["nom ev f"] },
	{ "word": "γυναικός", "cat": "γυνή", "answers": ["gen ev f"] },
	{ "word": "γυναικί", "cat": "γυνή", "answers": ["dat ev f"] },
	{ "word": "γυναῖκα", "cat": "γυνή", "answers": ["acc ev f"] },
	{ "word": "γυναῖκες", "cat": "γυνή", "answers": ["nom mv f"] },
	{ "word": "γυναικῶν", "cat": "γυνή", "answers": ["gen mv f"] },
	{ "word": "γυναιξί(ν)", "cat": "γυνή", "answers": ["dat mv f"] },
	{ "word": "γυναῖκας", "cat": "γυνή", "answers": ["acc mv f"] },
	{ "word": "λέων", "cat": "λέων", "answers": ["nom ev m"] },
	{ "word": "λέοντος", "cat": "λέων", "answers": ["gen ev m"] },
	{ "word": "λέοντι", "cat": "λέων", "answers": ["dat ev m"] },
	{ "word": "λέοντα", "cat": "λέων", "answers": ["acc ev m"] },
	{ "word": "λέοντες", "cat": "λέων", "answers": ["nom mv m"] },
	{ "word": "λεόντων", "cat": "λέων", "answers": ["gen mv m"] },
	{ "word": "λέουσι(ν)", "cat": "λέων", "answers": ["dat mv m"] },
	{ "word": "λέοντας", "cat": "λέων", "answers": ["acc mv m"] },
	{ "word": "σῶμα", "cat": "σῶμα", "answers": ["nom ev n", "acc ev n"] },
	{ "word": "σώματος", "cat": "σῶμα", "answers": ["gen ev n"] },
	{ "word": "σώματι", "cat": "σῶμα", "answers": ["dat ev n"] },
	{ "word": "σώματα", "cat": "σῶμα", "answers": ["nom mv n", "acc mv n"] },
	{ "word": "σωμάτων", "cat": "σῶμα", "answers": ["gen mv n"] },
	{ "word": "σώμασι(ν)", "cat": "σῶμα", "answers": ["dat mv n"] },

];

