const qWerkwoordLatijn = [
	{ word: "voco", cat: "vocare", answers: ["ind praes 1e-ev act"] },
	{ word: "vocas", cat: "vocare", answers: ["ind praes 2e-ev act"] },
	{ word: "vocat", cat: "vocare", answers: ["ind praes 3e-ev act"] },
	{ word: "vocamus", cat: "vocare", answers: ["ind praes 1e-mv act"] },
	{ word: "vocatis", cat: "vocare", answers: ["ind praes 2e-mv act"] },
	{ word: "vocant", cat: "vocare", answers: ["ind praes 3e-mv act"] },
	{ "word": "vocor", "cat": "vocare", "answers": ["ind praes 1e-ev pass"] },
	{ "word": "vocaris", "cat": "vocare", "answers": ["ind praes 2e-ev pass"] },
	{ "word": "vocatur", "cat": "vocare", "answers": ["ind praes 3e-ev pass"] },
	{ "word": "vocamur", "cat": "vocare", "answers": ["ind praes 1e-mv pass"] },
	{ "word": "vocamini", "cat": "vocare", "answers": ["ind praes 2e-mv pass"] },
	{ "word": "vocantur", "cat": "vocare", "answers": ["ind praes 3e-mv pass"] },
	{ "word": "vocabam", "cat": "vocare", "answers": ["ind impf 1e-ev act"] },
	{ "word": "vocabas", "cat": "vocare", "answers": ["ind impf 2e-ev act"] },
	{ "word": "vocabat", "cat": "vocare", "answers": ["ind impf 3e-ev act"] },
	{ "word": "vocabamus", "cat": "vocare", "answers": ["ind impf 1e-mv act"] },
	{ "word": "vocabatis", "cat": "vocare", "answers": ["ind impf 2e-mv act"] },
	{ "word": "vocabant", "cat": "vocare", "answers": ["ind impf 3e-mv act"] },
	{ "word": "vocabar", "cat": "vocare", "answers": ["ind impf 1e-ev pass"] },
	{ "word": "vocabaris", "cat": "vocare", "answers": ["ind impf 2e-ev pass"] },
	{ "word": "vocabatur", "cat": "vocare", "answers": ["ind impf 3e-ev pass"] },
	{ "word": "vocabamur", "cat": "vocare", "answers": ["ind impf 1e-mv pass"] },
	{ "word": "vocabamini", "cat": "vocare", "answers": ["ind impf 2e-mv pass"] },
	{ "word": "vocabantur", "cat": "vocare", "answers": ["ind impf 3e-mv pass"] },
	{ "word": "vocabo", "cat": "vocare", "answers": ["ind fut 1e-ev act"] },
	{ "word": "vocabis", "cat": "vocare", "answers": ["ind fut 2e-ev act"] },
	{ "word": "vocabit", "cat": "vocare", "answers": ["ind fut 3e-ev act"] },
	{ "word": "vocabimus", "cat": "vocare", "answers": ["ind fut 1e-mv act"] },
	{ "word": "vocabitis", "cat": "vocare", "answers": ["ind fut 2e-mv act"] },
	{ "word": "vocabunt", "cat": "vocare", "answers": ["ind fut 3e-mv act"] },
	{ "word": "vocabor", "cat": "vocare", "answers": ["ind fut 1e-ev pass"] },
	{ "word": "vocaberis", "cat": "vocare", "answers": ["ind fut 2e-ev pass"] },
	{ "word": "vocabitur", "cat": "vocare", "answers": ["ind fut 3e-ev pass"] },
	{ "word": "vocabimur", "cat": "vocare", "answers": ["ind fut 1e-mv pass"] },
	{ "word": "vocabimini", "cat": "vocare", "answers": ["ind fut 2e-mv pass"] },
	{ "word": "vocabuntur", "cat": "vocare", "answers": ["ind fut 3e-mv pass"] },
	{ "word": "vocavi", "cat": "vocare", "answers": ["ind perf 1e-ev act"] },
	{ "word": "vocavisti", "cat": "vocare", "answers": ["ind perf 2e-ev act"] },
	{ "word": "vocavit", "cat": "vocare", "answers": ["ind perf 3e-ev act"] },
	{ "word": "vocavimus", "cat": "vocare", "answers": ["ind perf 1e-mv act"] },
	{ "word": "vocavistis", "cat": "vocare", "answers": ["ind perf 2e-mv act"] },
	{ "word": "vocaverunt", "cat": "vocare", "answers": ["ind perf 3e-mv act"] },
	{ "word": "vocaveram", "cat": "vocare", "answers": ["ind plqpf 1e-ev act"] },
	{ "word": "vocaveras", "cat": "vocare", "answers": ["ind plqpf 2e-ev act"] },
	{ "word": "vocaverat", "cat": "vocare", "answers": ["ind plqpf 3e-ev act"] },
	{ "word": "vocaveramus", "cat": "vocare", "answers": ["ind plqpf 1e-mv act"] },
	{ "word": "vocaveratis", "cat": "vocare", "answers": ["ind plqpf 2e-mv act"] },
	{ "word": "vocaverant", "cat": "vocare", "answers": ["ind plqpf 3e-mv act"] },
	{ "word": "vocavero", "cat": "vocare", "answers": ["ind fex 1e-ev act"] },
	{ "word": "vocaveris", "cat": "vocare", "answers": ["ind fex 2e-ev act"] },
	{ "word": "vocaverit", "cat": "vocare", "answers": ["ind fex 3e-ev act"] },
	{ "word": "vocaverimus", "cat": "vocare", "answers": ["ind fex 1e-mv act"] },
	{ "word": "vocaveritis", "cat": "vocare", "answers": ["ind fex 2e-mv act"] },
	{ "word": "vocaverint", "cat": "vocare", "answers": ["ind fex 3e-mv act"] },
	{ "word": "vocem", "cat": "vocare", "answers": ["conj praes 1e-ev act"] },
	{ "word": "voces", "cat": "vocare", "answers": ["conj praes 2e-ev act"] },
	{ "word": "vocet", "cat": "vocare", "answers": ["conj praes 3e-ev act"] },
	{ "word": "vocemus", "cat": "vocare", "answers": ["conj praes 1e-mv act"] },
	{ "word": "vocetis", "cat": "vocare", "answers": ["conj praes 2e-mv act"] },
	{ "word": "vocent", "cat": "vocare", "answers": ["conj praes 3e-mv act"] },
	{ "word": "vocer", "cat": "vocare", "answers": ["conj praes 1e-ev pass"] },
	{ "word": "voceris", "cat": "vocare", "answers": ["conj praes 2e-ev pass"] },
	{ "word": "vocetur", "cat": "vocare", "answers": ["conj praes 3e-ev pass"] },
	{ "word": "vocemur", "cat": "vocare", "answers": ["conj praes 1e-mv pass"] },
	{ "word": "vocemini", "cat": "vocare", "answers": ["conj praes 2e-mv pass"] },
	{ "word": "vocentur", "cat": "vocare", "answers": ["conj praes 3e-mv pass"] },
	{ "word": "vocarem", "cat": "vocare", "answers": ["conj impf 1e-ev act"] },
	{ "word": "vocares", "cat": "vocare", "answers": ["conj impf 2e-ev act"] },
	{ "word": "vocaret", "cat": "vocare", "answers": ["conj impf 3e-ev act"] },
	{ "word": "vocaremus", "cat": "vocare", "answers": ["conj impf 1e-mv act"] },
	{ "word": "vocaretis", "cat": "vocare", "answers": ["conj impf 2e-mv act"] },
	{ "word": "vocarent", "cat": "vocare", "answers": ["conj impf 3e-mv act"] },
	{ "word": "vocarer", "cat": "vocare", "answers": ["conj impf 1e-ev pass"] },
	{ "word": "vocareris", "cat": "vocare", "answers": ["conj impf 2e-ev pass"] },
	{ "word": "vocaretur", "cat": "vocare", "answers": ["conj impf 3e-ev pass"] },
	{ "word": "vocaremur", "cat": "vocare", "answers": ["conj impf 1e-mv pass"] },
	{ "word": "vocaremini", "cat": "vocare", "answers": ["conj impf 2e-mv pass"] },
	{ "word": "vocarentur", "cat": "vocare", "answers": ["conj impf 3e-mv pass"] },
	{ "word": "vocaverim", "cat": "vocare", "answers": ["conj perf 1e-ev act"] },
	{ "word": "vocaveris", "cat": "vocare", "answers": ["conj perf 2e-ev act"] },
	{ "word": "vocaverit", "cat": "vocare", "answers": ["conj perf 3e-ev act"] },
	{ "word": "vocaverimus", "cat": "vocare", "answers": ["conj perf 1e-mv act"] },
	{ "word": "vocaveritis", "cat": "vocare", "answers": ["conj perf 2e-mv act"] },
	{ "word": "vocaverint", "cat": "vocare", "answers": ["conj perf 3e-mv act"] },
	{ "word": "voca", "cat": "vocare", "answers": ["imp praes 2e-ev act"] },
	{ "word": "vocate", "cat": "vocare", "answers": ["imp praes 2e-mv act"] },
	{ "word": "vocare", "cat": "vocare", "answers": ["inf praes x act"] },
	{ "word": "vocavisse", "cat": "vocare", "answers": ["inf perf x act"] },
	{ "word": "vocari", "cat": "vocare", "answers": ["inf praes x pass"] },
	{ "word": "vocare", "cat": "vocare", "answers": ["imp 2e-ev pass"] },

  

		
];

const questionsLatinNaamwoord = [
	{ word: "mensa", cat: "mensa", answers: ["nom ev f", "abl ev f"] },
	{ word: "mensae", cat: "mensa", answers: ["gen ev f", "dat ev f", "nom mv f"] },
	{ word: "mensam", cat: "mensa", answers: ["acc ev f"] },
	{ word: "mensarum", cat: "mensa", answers: ["gen mv f"] },
	{ word: "mensis", cat: "mensa", answers: ["dat mv f", "abl mv f"] },
	{ word: "mensas", cat: "mensa", answers: ["acc mv f"] },

	{ word: "servus", cat: "servus", answers: ["nom ev m"] },
	{ word: "servi", cat: "servus", answers: ["gen ev m", "nom mv m"] },
	{ word: "servo", cat: "servus", answers: ["dat ev m", "abl ev m"] },
	{ word: "servum", cat: "servus", answers: ["acc ev m"] },
	{ word: "servorum", cat: "servus", answers: ["gen mv m"] },
	{ word: "servis", cat: "servus", answers: ["dat mv m", "abl mv m"] },
	{ word: "servos", cat: "servus", answers: ["acc mv m"] },

	{ word: "donum", cat: "donum", answers: ["nom ev n", "acc ev n"] },
	{ word: "doni", cat: "donum", answers: ["gen ev n"] },
	{ word: "dono", cat: "donum", answers: ["dat ev n", "abl ev n"] },
	{ word: "dona", cat: "donum", answers: ["nom mv n", "acc mv n"] },
	{ word: "donorum", cat: "donum", answers: ["gen mv n"] },
	{ word: "donis", cat: "donum", answers: ["dat mv n", "abl mv n"] },

	{ word: "rex", cat: "rex", answers: ["nom ev m"] },
	{ word: "regis", cat: "rex", answers: ["gen ev m"] },
	{ word: "regi", cat: "rex", answers: ["dat ev m"] },
	{ word: "regem", cat: "rex", answers: ["acc ev m"] },
	{ word: "rege", cat: "rex", answers: ["abl ev m"] },
	{ word: "reges", cat: "rex", answers: ["nom mv m", "acc mv m"] },
	{ word: "regum", cat: "rex", answers: ["gen mv m"] },
	{ word: "regibus", cat: "rex", answers: ["dat mv m", "abl mv m"] },

	{ word: "nomen", cat: "nomen", answers: ["nom ev n", "acc ev n"] },
	{ word: "nominis", cat: "nomen", answers: ["gen ev n"] },
	{ word: "nomini", cat: "nomen", answers: ["dat ev n"] },
	{ word: "nomine", cat: "nomen", answers: ["abl ev n"] },
	{ word: "nomina", cat: "nomen", answers: ["nom mv n", "acc mv n"] },
	{ word: "nominum", cat: "nomen", answers: ["gen mv n"] },
	{ word: "nominbus", cat: "nomen", answers: ["dat mv n", "abl mv n"] },

	{ word: "bona", cat: "bonus", answers: ["nom ev f", "abl ev f", "nom mv n", "acc mv n"] },
	{ word: "bonae", cat: "bonus", answers: ["gen ev f", "dat ev f", "nom mv f"] },
	{ word: "bonam", cat: "bonus", answers: ["acc ev f"] },
	{ word: "bonarum", cat: "bonus", answers: ["gen mv f"] },
	{ word: "bonis", cat: "bonus", answers: ["dat mv f", "abl mv f", "dat mv m", "abl mv m", "dat mv n", "abl mv n"] },
	{ word: "bonas", cat: "bonus", answers: ["acc mv f"] },

	{ word: "bonus", cat: "bonus", answers: ["nom ev m"] },
	{ word: "boni", cat: "bonus", answers: ["gen ev m", "nom mv m", "gen ev n"] },
	{ word: "bono", cat: "bonus", answers: ["dat ev m", "abl ev m", "dat ev n", "abl ev n"] },
	{ word: "bonum", cat: "bonus", answers: ["acc ev m", "nom ev n", "acc ev n"] },
	{ word: "bonorum", cat: "bonus", answers: ["gen mv m", "gen mv n"] },
	{ word: "bonos", cat: "bonus", answers: ["acc mv m"] },

	{ word: "fortis", cat: "fortis", answers: ["nom ev m", "nom ev f", "gen ev m", "gen ev f", "gen ev n"] },
	{ word: "forti", cat: "fortis", answers: ["dat ev m", "dat ev f", "dat ev n", "abl ev m", "abl ev f", "abl ev n"] },
	{ word: "fortem", cat: "fortis", answers: ["acc ev m", "acc ev f"] },
	{ word: "fortes", cat: "fortis", answers: ["nom mv m", "nom mv f", "acc mv m", "acc mv f"] },
	{ word: "fortium", cat: "fortis", answers: ["gen mv m", "gen mv f", "gen mv n"] },
	{ word: "fortibus", cat: "fortis", answers: ["dat mv m", "abl mv m", "dat mv f", "abl mv f", "dat mv n", "abl mv n"] },
	{ word: "forte", cat: "fortis", answers: ["nom ev n", "acc ev n"] },
	{ word: "fortia", cat: "fortis", answers: ["nom mv n", "acc mv n"] },

	{ word: "ingens", cat: "ingens", answers: ["nom ev m", "nom ev f", "nom ev n", "acc ev n"] },
	{ word: "ingentis", cat: "ingens", answers: ["gen ev m", "gen ev f", "gen ev n"] },
	{ word: "ingenti", cat: "ingens", answers: ["dat ev m", "dat ev f", "dat ev n", "abl ev m", "abl ev f", "abl ev n"] },
	{ word: "ingentem", cat: "ingens", answers: ["acc ev m", "acc ev f"] },
	{ word: "ingentes", cat: "ingens", answers: ["nom mv m", "nom mv f", "acc mv m", "acc mv f"] },
	{ word: "ingentium", cat: "ingens", answers: ["gen mv m", "gen mv f", "gen mv n"] },
	{ word: "ingentibus", cat: "ingens", answers: ["dat mv m", "abl mv m", "dat mv f", "abl mv f", "dat mv n", "abl mv n"] },
	{ word: "ingentia", cat: "ingens", answers: ["nom mv n", "acc mv n"] },

];

const questionsGreekNaamwoord = [
	{ word: "ὁ", cat: "lidwoord", answers: ["nom ev m"] },
	{ word: "τοῦ", cat: "lidwoord", answers: ["gen ev m", "gen ev n"] },
	{ word: "τῷ", cat: "lidwoord", answers: ["dat ev m", "dat ev n"] },
	{ word: "τόν", cat: "lidwoord", answers: ["acc ev m"] },
	{ word: "οἱ", cat: "lidwoord", answers: ["nom mv m"] },
	{ word: "τῶν", cat: "lidwoord", answers: ["gen mv m", "gen mv f", "gen mv n"] },
	{ word: "τοῖς", cat: "lidwoord", answers: ["dat mv m", "dat mv n"] },
	{ word: "τούς", cat: "lidwoord", answers: ["acc mv m"] },
	{ word: "ἡ", cat: "lidwoord", answers: ["nom ev f"] },
	{ word: "τῆς", cat: "lidwoord", answers: ["gen ev f"] },
	{ word: "τῇ", cat: "lidwoord", answers: ["dat ev f"] },
	{ word: "τήν", cat: "lidwoord", answers: ["acc ev f"] },
	{ word: "αἱ", cat: "lidwoord", answers: ["nom mv f"] },
	{ word: "ταῖς", cat: "lidwoord", answers: ["dat mv f"] },
	{ word: "τάς", cat: "lidwoord", answers: ["acc mv f"] },
	{ word: "τό", cat: "lidwoord", answers: ["nom ev n", "acc ev n"] },
	{ word: "τά", cat: "lidwoord", answers: ["nom mv n", "acc mv n"] },
	{ word: "μάχη", cat: "μάχη", answers: ["nom ev f"] },
	{ word: "μάχης", cat: "μάχη", answers: ["gen ev f"] },
	{ word: "μάχῃ", cat: "μάχη", answers: ["dat ev f"] },
	{ word: "μάχην", cat: "μάχη", answers: ["acc ev f"] },
	{ word: "μάχαι", cat: "μάχη", answers: ["nom mv f"] },
	{ word: "μαχῶν", cat: "μάχη", answers: ["gen mv f"] },
	{ word: "μάχαις", cat: "μάχη", answers: ["dat mv f"] },
	{ word: "μάχας", cat: "μάχη", answers: ["acc mv f"] },
	{ word: "χώρα", cat: "χώρα", answers: ["nom ev f"] },
	{ word: "χώρας", cat: "χώρα", answers: ["gen ev f", "acc mv f"] },
	{ word: "χώρᾳ", cat: "χώρα", answers: ["dat ev f"] },
	{ word: "χώραν", cat: "χώρα", answers: ["acc ev f"] },
	{ word: "χῶραι", cat: "χώρα", answers: ["nom mv f"] },
	{ word: "χωρῶν", cat: "χώρα", answers: ["gen mv f"] },
	{ word: "χώραις", cat: "χώρα", answers: ["dat mv f"] },
	{ word: "θάλαττα", cat: "θάλαττα", answers: ["nom ev f"] },
	{ word: "θαλάττης", cat: "θάλαττα", answers: ["gen ev f"] },
	{ word: "θαλάττῃ", cat: "θάλαττα", answers: ["dat ev f"] },
	{ word: "θάλατταν", cat: "θάλαττα", answers: ["acc ev f"] },
	{ word: "θάλατται", cat: "θάλαττα", answers: ["nom mv f"] },
	{ word: "θαλαττῶν", cat: "θάλαττα", answers: ["gen mv f"] },
	{ word: "θαλάτταις", cat: "θάλαττα", answers: ["dat mv f"] },
	{ word: "θαλάττας", cat: "θάλαττα", answers: ["acc mv f"] },
	{ word: "δεσπότης", cat: "δεσπότης", answers: ["nom ev m"] },
	{ word: "δεσπότου", cat: "δεσπότης", answers: ["gen ev m"] },
	{ word: "δεσπότῃ", cat: "δεσπότης", answers: ["dat ev m"] },
	{ word: "δεσπότην", cat: "δεσπότης", answers: ["acc ev m"] },
	{ word: "δεσπόται", cat: "δεσπότης", answers: ["nom mv m"] },
	{ word: "δεσποτῶν", cat: "δεσπότης", answers: ["gen mv m"] },
	{ word: "δεσπόταις", cat: "δεσπότης", answers: ["dat mv m"] },
	{ word: "δεσπότας", cat: "δεσπότης", answers: ["acc mv m"] },
	{ word: "δοῦλος", cat: "δοῦλος", answers: ["nom ev m"] },
	{ word: "δούλου", cat: "δοῦλος", answers: ["gen ev m"] },
	{ word: "δούλῳ", cat: "δοῦλος", answers: ["dat ev m"] },
	{ word: "δοῦλον", cat: "δοῦλος", answers: ["acc ev m"] },
	{ word: "δοῦλοι", cat: "δοῦλος", answers: ["nom mv m"] },
	{ word: "δούλων", cat: "δοῦλος", answers: ["gen mv m"] },
	{ word: "δούλοις", cat: "δοῦλος", answers: ["dat mv m"] },
	{ word: "δούλους", cat: "δοῦλος", answers: ["acc mv m"] },
	{ word: "θηρίον", cat: "θηρίον", answers: ["nom ev n", "acc ev n"] },
	{ word: "θηρίου", cat: "θηρίον", answers: ["gen ev n"] },
	{ word: "θηρίῳ", cat: "θηρίον", answers: ["dat ev n"] },
	{ word: "θηρία", cat: "θηρίον", answers: ["nom mv n", "acc mv n"] },
	{ word: "θηρίων", cat: "θηρίον", answers: ["gen mv n"] },
	{ word: "θηρίοις", cat: "θηρίον", answers: ["dat mv n"] },
	{ word: "σωτήρ", cat: "σωτήρ", answers: ["nom ev m"] },
	{ word: "σωτῆρος", cat: "σωτήρ", answers: ["gen ev m"] },
	{ word: "σωτῆρι", cat: "σωτήρ", answers: ["dat ev m"] },
	{ word: "σωτῆρα", cat: "σωτήρ", answers: ["acc ev m"] },
	{ word: "σωτῆρες", cat: "σωτήρ", answers: ["nom mv m"] },
	{ word: "σωτήρων", cat: "σωτήρ", answers: ["gen mv m"] },
	{ word: "σωτῆρσι(ν)", cat: "σωτήρ", answers: ["dat mv m"] },
	{ word: "σωτῆρα", cat: "σωτήρ", answers: ["acc mv m"] },
	{ word: "γυνή", cat: "γυνή", answers: ["nom ev f"] },
	{ word: "γυναικός", cat: "γυνή", answers: ["gen ev f"] },
	{ word: "γυναικί", cat: "γυνή", answers: ["dat ev f"] },
	{ word: "γυναῖκα", cat: "γυνή", answers: ["acc ev f"] },
	{ word: "γυναῖκες", cat: "γυνή", answers: ["nom mv f"] },
	{ word: "γυναικῶν", cat: "γυνή", answers: ["gen mv f"] },
	{ word: "γυναιξί(ν)", cat: "γυνή", answers: ["dat mv f"] },
	{ word: "γυναῖκας", cat: "γυνή", answers: ["acc mv f"] },
	{ word: "λέων", cat: "λέων", answers: ["nom ev m"] },
	{ word: "λέοντος", cat: "λέων", answers: ["gen ev m"] },
	{ word: "λέοντι", cat: "λέων", answers: ["dat ev m"] },
	{ word: "λέοντα", cat: "λέων", answers: ["acc ev m"] },
	{ word: "λέοντες", cat: "λέων", answers: ["nom mv m"] },
	{ word: "λεόντων", cat: "λέων", answers: ["gen mv m"] },
	{ word: "λέουσι(ν)", cat: "λέων", answers: ["dat mv m"] },
	{ word: "λέοντας", cat: "λέων", answers: ["acc mv m"] },
	{ word: "σῶμα", cat: "σῶμα", answers: ["nom ev n", "acc ev n"] },
	{ word: "σώματος", cat: "σῶμα", answers: ["gen ev n"] },
	{ word: "σώματι", cat: "σῶμα", answers: ["dat ev n"] },
	{ word: "σώματα", cat: "σῶμα", answers: ["nom mv n", "acc mv n"] },
	{ word: "σωμάτων", cat: "σῶμα", answers: ["gen mv n"] },
	{ word: "σώμασι(ν)", cat: "σῶμα", answers: ["dat mv n"] },

];

